devices:
  - id: HNT001

  - id: HNT002

  - id: HNT003

monitoring_sites:
  - id: GF_STREAM_FEEDER
    name: Grandfather's - Stream feeder
    coordinates: [0, 0]

  - id: GF_STREAM_DRINK_ZONE
    name: Grandfather's - Stream drink zone
    coordinates: [0, 0]

  - id: GF_RIVER_OAKS_FOREST
    name: Grandfather's - River oaks forest
    coordinates: [0, 0]

  - id: CASCABEL_RIVERSIDE
    name: Cascabel - Riverside
    coordinates: [0, 0]
