camera_locations:
  - id: HOMELAND_FALLEN_TREE
    name: Homeland - Fallen tree
    coordinates: [0, 0]

  - id: HOMELAND_MAIN_WOODS
    name: Homeland - Main woods
    coordinates: [0, 0]

  - id: GF_STREAM_FEEDER
    name: Grandfather's - Stream feeder
    coordinates: [0, 0]

  - id: GF_STREAM_DRINK_ZONE
    name: Grandfather's - Stream drink zone
    coordinates: [0, 0]

  - id: CASCABEL_RIVERSIDE
    name: Cascabel - Riverside
    coordinates: [0, 0]
